### ISSUE TITLE
TASK [rails : Precompile assets] aborted. RuntimeError

### ISSUE THREAD

**Issue by fpavon777** [consul/installer#178]
Hi. Please, I need help!!!!

Using installer I get this error. Ubuntu 18.04

cmd: source /home/deploy/.rvm/scripts/rvm && bin/rake assets:precompile RAILS_ENV=production
  delta: '0:07:07.038350'
  end: '2021-05-18 14:25:03.001210'
  msg: non-zero return code
  rc: 1
  start: '2021-05-18 14:17:55.962860'
  stderr: |-
    rake aborted!
    ExecJS::RuntimeError:
    (execjs):1
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:219:in `exec_runtime'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/compressing.rb:65:in `block in js_compressor='
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy_proc_processor.rb:31:in `call'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
    /home/deploy/consul/shared/bundle/ruby/2.6.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
    Tasks: TOP => assets:precompile
    (See full trace by running task with --trace)
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by javierm** [comment]
Hi, @fpavon777.

One possible cause for this error is the server is running out of RAM when compiling the assets :thinking:. How much RAM do you have on the server?

**Comment by fpavon777** [comment]
Thanks for answering

The server is a EC2 instance. It has 1 Gb. is it necessary to have more memory?

**Comment by Senen** [comment]
Hi @fpavon777, I installed CONSUL in EC2 instances a few times, and the minimum EC2 type that worked fine was a `t2.small` which has 2GB of RAM; if you want to be sure, you can use a `t2.medium` which has 4GB of RAM.

**Comment by javierm** [comment]
There are precedents of getting the error on a machine with 2GB, so yeah, if you want to be sure, for testing purposes we recommend at least 4GB. For production sites, it will depend on the traffic you get.

**Comment by fpavon777** [comment]
It worked!!!! I have created an instance with 4 GB

It seems to have been installed well. This is the output

PLAY RECAP **************************************
ok=87   changed=58   unreachable=0    failed=0    skipped=52   rescued=0    ignored=0

Is it ok?

**Comment by javierm** [comment]
Glad it worked :smile:. Yes, the output seems OK, although the real proof is opening the page in a web browser and checking it worked.

**Comment by fpavon777** [comment]
Must I use the port 3000, right?

**Comment by javierm** [comment]
No, on production we use the standard port 80. The port 3000 is used while developing the application in your local machine.
