### ISSUE TITLE
Task  Install gems  Fails 

### ISSUE THREAD

**Issue by jesuxgslp** [consul/installer#42]
Scenario, libs and versions :

Local Machine:
Ubuntu 16.04.4 LTS
ruby 2.3
usuario local: user
simplejson 3.8.1
ansible 2.5.4

Remote server:
Ubuntu 16.04.4 LTS
ruby 2.3
user: deploy (created by ansible )
python-simplejson 3.8.1
Ubuntu 16.04 x64

TASK [capistrano : Install gems (this may take a few minutes)] *********************************************************************************************************************************************
fatal: [10.99.52.80]: FAILED! => {"changed": true, "cmd": "gem install bundler && bundle install", "delta": "0:00:17.052788", "end": "2018-06-27 12:06:38.257560", "msg": "non-zero return code", "rc": 5, "start": "2018-06-27 12:06:21.204772", "stderr": "", "stderr_lines": [], "stdout": "Successfully installed bundler-1.16.2\nParsing documentation for bundler-1.16.2\nDone installing documentation for bundler after 3 seconds\n1 gem installed\nDon't run Bundler as root. Bundler can ask for sudo if it is needed, and\ninstalling your bundle as root will break this application for all non-root\nusers on this machine.\nFetching gem metadata from https://rails-assets.org/..\nFetching gem metadata from https://rubygems.org/...........\nFetching gem metadata from https://rails-assets.org/..\nUsing rake 12.3.1\nUsing concurrent-ruby 1.0.5\nUsing i18n 0.9.1\nUsing minitest 5.11.1\nUsing thread_safe 0.3.6\nUsing tzinfo 1.2.4\nUsing activesupport 4.2.10\nUsing builder 3.2.3\nUsing erubis 2.7.0\nUsing mini_portile2 2.3.0\nFetching nokogiri 1.8.2\nInstalling nokogiri 1.8.2 with native extensions\nGem::Ext::BuildError: ERROR: Failed to build gem native extension.\n\n    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.2/ext/nokogiri\n/usr/bin/ruby2.3 -r ./siteconf20180627-6654-k2t6v1.rb extconf.rb\nmkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h\n\nextconf failed, exit code 1\n\nGem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.8.2 for\ninspection.\nResults logged to\n/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.2/gem_make.out\n\nAn error occurred while installing nokogiri (1.8.2), and Bundler cannot\ncontinue.\nMake sure that `gem install nokogiri -v '1.8.2'` succeeds before bundling.\n\nIn Gemfile:\n  graphiql-rails was resolved to 1.4.8, which depends on\n    rails was resolved to 4.2.10, which depends on\n      actionmailer was resolved to 4.2.10, which depends on\n        actionpack was resolved to 4.2.10, which depends on\n          actionview was resolved to 4.2.10, which depends on\n            rails-dom-testing was resolved to 1.0.9, which depends on\n              nokogiri", "stdout_lines": ["Successfully installed bundler-1.16.2", "Parsing documentation for bundler-1.16.2", "Done installing documentation for bundler after 3 seconds", "1 gem installed", "Don't run Bundler as root. Bundler can ask for sudo if it is needed, and", "installing your bundle as root will break this application for all non-root", "users on this machine.", "Fetching gem metadata from https://rails-assets.org/..", "Fetching gem metadata from https://rubygems.org/...........", "Fetching gem metadata from https://rails-assets.org/..", "Using rake 12.3.1", "Using concurrent-ruby 1.0.5", "Using i18n 0.9.1", "Using minitest 5.11.1", "Using thread_safe 0.3.6", "Using tzinfo 1.2.4", "Using activesupport 4.2.10", "Using builder 3.2.3", "Using erubis 2.7.0", "Using mini_portile2 2.3.0", "Fetching nokogiri 1.8.2", "Installing nokogiri 1.8.2 with native extensions", "Gem::Ext::BuildError: ERROR: Failed to build gem native extension.", "", "    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.2/ext/nokogiri", "/usr/bin/ruby2.3 -r ./siteconf20180627-6654-k2t6v1.rb extconf.rb", "mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h", "", "extconf failed, exit code 1", "", "Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.8.2 for", "inspection.", "Results logged to", "/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.2/gem_make.out", "", "An error occurred while installing nokogiri (1.8.2), and Bundler cannot", "continue.", "Make sure that `gem install nokogiri -v '1.8.2'` succeeds before bundling.", "", "In Gemfile:", "  graphiql-rails was resolved to 1.4.8, which depends on", "    rails was resolved to 4.2.10, which depends on", "      actionmailer was resolved to 4.2.10, which depends on", "        actionpack was resolved to 4.2.10, which depends on", "          actionview was resolved to 4.2.10, which depends on", "            rails-dom-testing was resolved to 1.0.9, which depends on", "              nokogiri"]}
	to retry, use: --limit @/home/jesux/projects/installer/consul.retry

**Comment by jesuxgslp** [comment]
No, I am going to try a manual installation

**Comment by bracintosh** [comment]
@jesuxgslp I see. I solved a lot of issues by modifying the `main.yml` file inside `roles/capistrano/tasks`, what I did was replace the **deploy** user with **root**. But now I'm facing SSH issues when executing **cap deploy production**.

**Comment by TheCoffeMaker** [comment]
Got it running using @warringaa 's fix. But now I'm getting this comment while running the ```TASK [rails : Precompile assets]```

```
"Autoprefixer doesn't support Node v4.2.6. Update it"
```

**Comment by TheCoffeMaker** [comment]
This is the complete output

```
TASK [rails : Precompile assets] *********************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "source /home/deploy/.rvm/scripts/rvm && bin/rake assets:precompile RAILS_ENV=production", "delta": "0:00:11.252724", "end": "2018-09-18 12:57:49.233178", "msg": "non-zero return code", "rc": 1, "start": "2018-09-18 12:57:37.980454", "stderr": "Running via Spring preloader in process 7092\nI, [2018-09-18T12:57:39.292850 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ckeditor/config-2afa5154111f645ccbda52644cb9b734c1e0e610778060935b16709f694a8458.js\nI, [2018-09-18T12:57:39.294379 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ckeditor/config-2afa5154111f645ccbda52644cb9b734c1e0e610778060935b16709f694a8458.js.gz\nI, [2018-09-18T12:57:40.016189 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ie_lt9-e4cf4bec58ff72856ebb3c489768d95a3905f4956c4085904782c29ff0f8b8ef.js\nI, [2018-09-18T12:57:40.016349 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ie_lt9-e4cf4bec58ff72856ebb3c489768d95a3905f4956c4085904782c29ff0f8b8ef.js.gz\nI, [2018-09-18T12:57:48.443409 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/stat_graphs-9be20f723d9023f19705b07c9d393827a51675edce4214712caa208d2b60b062.js\nI, [2018-09-18T12:57:48.443608 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/stat_graphs-9be20f723d9023f19705b07c9d393827a51675edce4214712caa208d2b60b062.js.gz\nrake aborted!\nAutoprefixer doesn?t support Node v4.2.6. Update it.\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:163:in `runtime'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:37:in `process'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:20:in `run'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:14:in `call'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'\n/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'\n-e:1:in `<main>'\nTasks: TOP => assets:precompile\n(See full trace by running task with --trace)", "stderr_lines": ["Running via Spring preloader in process 7092", "I, [2018-09-18T12:57:39.292850 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ckeditor/config-2afa5154111f645ccbda52644cb9b734c1e0e610778060935b16709f694a8458.js", "I, [2018-09-18T12:57:39.294379 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ckeditor/config-2afa5154111f645ccbda52644cb9b734c1e0e610778060935b16709f694a8458.js.gz", "I, [2018-09-18T12:57:40.016189 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ie_lt9-e4cf4bec58ff72856ebb3c489768d95a3905f4956c4085904782c29ff0f8b8ef.js", "I, [2018-09-18T12:57:40.016349 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/ie_lt9-e4cf4bec58ff72856ebb3c489768d95a3905f4956c4085904782c29ff0f8b8ef.js.gz", "I, [2018-09-18T12:57:48.443409 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/stat_graphs-9be20f723d9023f19705b07c9d393827a51675edce4214712caa208d2b60b062.js", "I, [2018-09-18T12:57:48.443608 #7092]  INFO -- : Writing /home/deploy/consul/public/assets/stat_graphs-9be20f723d9023f19705b07c9d393827a51675edce4214712caa208d2b60b062.js.gz", "rake aborted!", "Autoprefixer doesn?t support Node v4.2.6. Update it.", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:163:in `runtime'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/processor.rb:37:in `process'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:20:in `run'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/autoprefixer-rails-9.1.4/lib/autoprefixer-rails/sprockets.rb:14:in `call'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'", "/home/deploy/.rvm/gems/ruby-2.3.2/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'", "-e:1:in `<main>'", "Tasks: TOP => assets:precompile", "(See full trace by running task with --trace)"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/deploy/installer/consul.retry

PLAY RECAP *******************************************************************************************************************************************************************
127.0.0.1                  : ok=54   changed=34   unreachable=0    failed=1   

```

**Comment by voodoorai2000** [comment]
Hey @TheCoffeMaker!

Indeed! Thank so much for letting us know!

Sending a PR updating the Node library in the installer  👍
We'll post a comment here as soon as it's ready 🙏

**Comment by voodoorai2000** [comment]
Hey @TheCoffeMaker!
Could you update the Installer and give it another try? 😌

**Comment by TheCoffeMaker** [comment]
I there @voodoorai2000 ! I have tried again .... and guess what ... it works!!!!

**Comment by voodoorai2000** [comment]
Fantastic! Very happy to hear that @TheCoffeMaker! 😃🎉
